version: 2.1
jobs:
  build_and_test:
    working_directory: ~/backend
    docker:
      - image: cimg/php:7.3.20-node
      - image: circleci/mysql:8.0
        environment:
          MYSQL_DATABASE: db
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
    steps:
      - checkout:
          path: ~/backend
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "backend/composer.lock" }}
            - composer-v1-
      # - run: composer install -n --prefer-dist

      - save_cache:
          key: composer-v1-{{ checksum "backend/composer.lock" }}
          paths:
            - ./vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "backend/package-lock.json" }}
            - node-v1-
      - run:
          name: node_modules依存関係をインストール
          command: npm install
      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: .envファイルを復元
          command: echo $ENV_FILE | base64 --decode > .env
      - run:
          name: マイグレーションを実行
          command: vendor/bin/phpunit --testdox-xml test_results/phpunit/result.xml --coverage-html=coverage
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results
      - store_artifacts:
          path: coverage

workflows:
  main:
    jobs:
      - build_and_test
